fizzbuzz.rbを作成し、FizzBuzzプログラムを書きました
hirokiej/ruby-practices pull request #1
Opened 2024-01-12 03:45 UTC by hirokiej

FizzBuzzの提出物です。
fizzbuzz.rbにコードを書きましたのでご確認よろしくお願い致します。

2024-01-18 16:27 UTC, u1tnk requested changes

2024-01-18 16:27 UTC, u1tnk commented on 01.fizzbuzz/fizzbuzz.rb
> +20.times do |number
numberの後に `|` が無いのでエラーにならないですか？

2024-01-18 16:27 UTC, u1tnk commented on 01.fizzbuzz/fizzbuzz.rb
> +  true_number = number + 1
意図は伝わりますが、true_numberは抽象的でちょっと名前が良くないですね。
良くない名前をつけるぐらいなら全部 `number + 1` の方が良いですね。
他には `1..20` を使うと1からにできますね。

2024-01-18 19:40 UTC, hirokiej commented on 01.fizzbuzz/fizzbuzz.rb
> +20.times do |number
ありがとうございます
エラーになりました…
どのタイミングで消してしまったのかわかりませんが修正いたします。

2024-01-18 19:41 UTC, hirokiej commented on 01.fizzbuzz/fizzbuzz.rb
> +  true_number = number + 1
ありがとうございます！
`(1..20)`の方が見た目がすっきりするので、そちらで書き直します。
`number+1`の方も自身で試してみて無事実行することができました。
これから`push`します。

2024-01-18 19:45 UTC, hirokiej commented
`|`を追加し、`(1..20)`でコードの修正をいたしました。
ご確認よろしくお願い致します。

2024-01-19 02:34 UTC, u1tnk approved these changes

2024-01-19 19:42 UTC, merged