bowling.rbを作成しました。
hirokiej/ruby-practices pull request #3
Opened 2024-02-06 03:03 UTC by hirokiej

ボウリングスコア計算プログラムの提出物です。
ご確認よろしくお願いいたします。

2024-02-12 15:50 UTC, u1tnk requested changes

2024-02-12 15:50 UTC, u1tnk commented on 03.bowling/bowling.rb
> +frames.each_with_index do |frame, index|
これ最終フレームのストライク/スペアのケースカバーされてますでしょうか？

2024-02-13 06:11 UTC, hirokiej commented on 03.bowling/bowling.rb
> +frames.each_with_index do |frame, index|
計算ができたから大丈夫だと思ってましたが、ご指摘いただいて、これ、最終フレームの後に2回投げてたら計算できてしまうということですね。
ご指摘ありがとうございます。
修正いたしました。

2024-02-15 17:03 UTC, u1tnk approved these changes

2024-02-20 06:16 UTC, merged